# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elan CI 

on:
  workflow_dispatch:
  push:
    tags:
      - 'release-liepa3-[0-9]+.[0-9]+.[0-9]+'

jobs:

  set-release-version:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.extract_version.outputs.ELAN_RELEASE_VERSION }}
    steps:
      - id: extract_version
        run: |
          TAG=${GITHUB_REF_NAME}
          echo "TAG: $TAG"
          ELAN_RELEASE_VERSION=${TAG#release-liepa3-}
          echo "ELAN_RELEASE_VERSION: $ELAN_RELEASE_VERSION"
          echo "ELAN_RELEASE_VERSION=${ELAN_RELEASE_VERSION}" >> "$GITHUB_OUTPUT"
      
        
       
##########################################

  build-linux-installer:

    runs-on: ubuntu-latest
    name: Build Installer on Linux
    needs: [set-release-version]
    env:
      ELAN_RELEASE_VERSION: ${{ needs.set-release-version.outputs.release_version }}
    steps:
      
    - name: Extract Version
      run: |
        echo "ELAN_RELEASE_VERSION: $ELAN_RELEASE_VERSION"
        echo "needs.set-release-version.outputs.release_version: ${{needs.set-release-version.outputs.release_version}}"

    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        echo "ELAN_RELEASE_VERSION: ${{ env.ELAN_RELEASE_VERSION }}"
        echo "ELAN_RELEASE_VERSION: ${ELAN_RELEASE_VERSION}"
        mvn -v
        mvn -B package --file pom.xml -Dexec.phase=install
        mkdir -p ./target/jpackage-input
        cp target/elan-6.9.jar ./target/jpackage-input
        cp -r ./target/lib ./target/jpackage-input/lib
        jpackage --verbose "@jpackage.cfg" "@jpackage-linux-deb.cfg" --app-version ${ELAN_RELEASE_VERSION}
        jpackage --verbose "@jpackage.cfg" "@jpackage-linux-appimage.cfg" --app-version ${ELAN_RELEASE_VERSION}


    # SAVE INSTALLER
    - id: upload-installer
      name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        path: target/elan_${{ env.ELAN_RELEASE_VERSION }}_amd64.deb
        name: linux-installer
        retention-days: 1

    - id: upload-linux-appimage
      name: Upload Linux AppImage
      uses: actions/upload-artifact@v4
      with:
        path: target/jpackage-output-linux
        name: linux-appimage
        retention-days: 1

###################################################

  build-windows-installer:
    name: Build Installer on Windows
    needs: [set-release-version]
    runs-on: windows-latest
    env:
      ELAN_RELEASE_VERSION: ${{ needs.set-release-version.outputs.release_version }}
    steps:


# SETUP BUILD ENVIRONMENT
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v3
    - id: setup-jdk
      name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21

# BUILD FOR DISTRIBUTION
    - id: build
      name: Build distribution
      run: |
        pwd
        echo %cd%
        echo "get_ELAN_RELEASE_VERSION ${{ env.ELAN_RELEASE_VERSION }}"
        mvn -v
        mvn -B package --file pom.xml -D"exec.phase=install" -D"maven.test.skip"
        mkdir -p ./target/jpackage-input
        cp target/elan-6.9.jar ./target/jpackage-input
        cp -r ./target/lib ./target/jpackage-input/lib
        jpackage --verbose "@jpackage.cfg" "@jpackage-win.cfg" --app-version ${{ env.ELAN_RELEASE_VERSION }}
        jpackage --verbose "@jpackage.cfg" "@jpackage-win-appimage.cfg" --app-version ${{ env.ELAN_RELEASE_VERSION }}

# SAVE INSTALLER
    - id: upload-installer
      name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        path: target/ELAN-${{ env.ELAN_RELEASE_VERSION }}.msi
        name: windows-installer
        retention-days: 1


    - id: upload-win-appimage
      name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        path: target/jpackage-output-win
        name: windows-appimage
        retention-days: 1


###############################

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [set-release-version, build-linux-installer, build-windows-installer]
    env:
      ELAN_RELEASE_VERSION: ${{ needs.set-release-version.outputs.release_version }}
    steps:
    - name: Extract Version
      run: |
        echo "ELAN_RELEASE_VERSION: $ELAN_RELEASE_VERSION"

     #DOWNLOAD INSTALLERS
    - id: download-linux-installer
      name: Download Linux installer
      uses: actions/download-artifact@v4
      with:
        name: linux-installer
        
    - id: download-linux-appimage
      name: Download Linux AppImage
      uses: actions/download-artifact@v4
      with:
        name: linux-appimage

    - id: download-windows-installer
      name: Download Windows installer
      uses: actions/download-artifact@v4
      with:
        name: windows-installer
        
    - id: zip-linux-appimage 
      run: |
        mv -v ELAN ELAN-${{ env.ELAN_RELEASE_VERSION }}
        chmod a+x ELAN-${{ env.ELAN_RELEASE_VERSION }}/bin/ELAN
        tar -czf ELAN-${{ env.ELAN_RELEASE_VERSION }}.linux.tar.gz ELAN-${{ env.ELAN_RELEASE_VERSION }}
        rm -rfv  ELAN-${{ env.ELAN_RELEASE_VERSION }}
        ls -l

    - id: download-win-appimage
      name: Download Windows AppImage
      uses: actions/download-artifact@v4
      with:
        name: windows-appimage

    - id: zip-win-appimage 
      run: |
        mv -v ELAN ELAN-${{ env.ELAN_RELEASE_VERSION }}
        zip -qq -r ELAN-${{ env.ELAN_RELEASE_VERSION }}.win.zip ELAN-${{ env.ELAN_RELEASE_VERSION }}
        rm -rfv  ELAN-${{ env.ELAN_RELEASE_VERSION }}
        ls -l

    - id: list-downloaded-files
      run: ls -l

# CREATE GITHUB RELEASE AND ADD ASSETS
    # - id: tag
    #   name: Move latest-release tag
    #   shell: bash
    #   if: false
    #   run: |
    #     # Move tag
    #     git tag -d latest-release
    #     git push --delete origin latest-release
    #     git tag -a latest-release -m "Latest of a Release"
    #     git push --follow-tags
    - id: create-release
      name: Create GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: true
    - id: release-linux-installer
      name: Release Linux installer
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: elan_${{ env.ELAN_RELEASE_VERSION }}_amd64.deb
        asset_name: elan_${{ env.ELAN_RELEASE_VERSION }}_amd64.deb
        asset_content_type: application/x-binary
    - id: release-windows-installer
      name: Release Windows installer
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ELAN-${{ env.ELAN_RELEASE_VERSION }}.msi
        asset_name: ELAN-${{ env.ELAN_RELEASE_VERSION }}.msi
        asset_content_type: application/x-binary
        
    - id: release-linux-appimage
      name: Release Linux AppImage
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ELAN-${{ env.ELAN_RELEASE_VERSION }}.linux.tar.gz
        asset_name: ELAN-${{  env.ELAN_RELEASE_VERSION }}.linux.tar.gz
        asset_content_type: application/x-binary        


    - id: release-win-appimage
      name: Release Windows AppImage
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ELAN-${{ env.ELAN_RELEASE_VERSION }}.win.zip
        asset_name: ELAN-${{  env.ELAN_RELEASE_VERSION }}.win.zip
        asset_content_type: application/x-binary        
